name: Lint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
        run:
          working-directory: subdir
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        make install
    - name: Commit Range
      id: commit-range
      uses: akaihola/darker/.github/actions/commit-range@1.7.1
    - name: Format (darker)
      run: |
        DIFF="--diff" CHECK="--check" REVISION="--revision='${{ steps.commit-range.outputs.commit-range }}'" make format
