name: Lint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: subdir
    strategy:
      matrix:
        include:
          - dir: "subsubdir"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        make install
    - uses: akaihola/darker@v2.1.1
      with:
        options: "--check --diff --isort --color"
        src: "subdir/${{ matrix.dir }}"
        version: "~=2.1.1"
